# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ziyi-Record
email: kwokjona@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <b>Ziyi Guo</b>, from China Mainland, doing Summer job in <b>HIIT</b>
  --Helsinki Institute for Information Technolofy,Finland.
  I'm working on front-end developing with AngularJS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ziyi-guo.github.io" # the base hostname & protocol for your site
facebook_username: Ziyi Guo
github_username:  Ziyi-Guo

# Build settings
markdown: kramdown

# other config
timezone: Europe/Helsinki

#defaults for posts
defaults:
 -
  scope:
    path: "_posts"
  values:
    layout: "post"
