# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ziyi-Record
email: kwokjona@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <b>Ziyi Guo</b>, from China Mainland, doing the exchange in Aalto University,
  Finland. I'm doing my bachelor thesis on Computer Vision, learning Hadoop
  at the same time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ziyi-guo.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  Ziyi-Guo

# Build settings
markdown: kramdown
