# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
<<<<<<< HEAD
title: Ziyi-Record
email: kwokjona@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <b>Ziyi Guo</b>, from China Mainland, doing the exchange in Aalto University,
  Finland. I'm doing my bachelor thesis on Computer Vision, learning Hadoop
  at the same time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ziyi-guo.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  Ziyi-Guo
=======
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
>>>>>>> eafdc51c3ec39a1334fca1ffd4a6c95d32976ecd

# Build settings
markdown: kramdown
